# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$os\
$sudo\
$username\
$hostname\
$localip\
$directory\
$docker_context\
$git_branch\
$git_commit\
$git_metrics\
$git_status\
$line_break$character"""
right_format = "$all"

# Git
[git_branch]
format = '[$symbol($remote_branch@)$branch ]($style)'
always_show_remote = true
symbol = 'ï„¦ '
style = 'bold #F34F29'

[git_metrics]
added_style = 'bold #F34F29'
deleted_style = 'bold #F34F29'

[git_state]
style = 'bold #F34F29'

[git_status]
format = '[ï’¥ $all_status (ó±“ $ahead_behind )]($style)'
# File status
conflicted = 'C'
untracked = 'U'
stashed = 'S'
modified = 'M'
staged = 'T'
renamed = 'R'
deleted = 'D'
# Checkout status
ahead = 'ï“š '
behind = 'ï“™ '
diverged = 'ï’Œ '
up_to_date = 'ó°“¦ '
style = 'bold #F34F29'

# Programming Language
[bun]
format = '[$symbol($version )]($style)'
symbol = 'î¯ '
style = 'bold 226'

[c]
format = '[$symbol($version-($name) )]($style)'
symbol = 'î± '
style = 'bold 27'

[cmake]
format = '[$symbol($version )]($style)'
symbol = 'î” '
style = 'bold bright-blue'

[dart]
format = '[$symbol($version )]($style)'
symbol = 'î™Œ '
style = 'bold 33'

[deno]
format = '[$symbol($version )]($style)'
symbol = 'îŸ€ '
style = 'bold 76'

[docker_context]
format = '[$symbol$context ]($style)'
symbol = 'ïˆŸ '
style = 'bold 27'

[dotnet]
format = '[$symbol($version )(ó°“¾ $tfm )]($style)'
symbol = 'ó°ª® '
style = 'bold 93'

[elixir]
format = '[$symbol($version \(OTP $otp_version\) )]($style)'
symbol = 'î˜­ '
style = 'bold 92'

[java]
format = '[$symbol($version) ]($style)'
symbol = 'îœ¸ '
style = 'bold 88'

[kotlin]
format = '[$symbol($version) ]($style)'
symbol = 'î˜´ '
style = 'bold 92'

[lua]
format = '[$symbol($version) ]($style)'
symbol = 'î ¦ '
style = 'bold 20'

[nodejs]
format = '[$symbol($version) ]($style)'
symbol = 'î´ '
style = 'bold 40'

[python]
format = '[$symbol$pyenv_prefix ($version )(\($virtualenv\) )]($style)'
symbol = 'îœ¼ '
detect_folders = ['.venv', '.env']
style = 'bold 220'

[rust]
format = '[$symbol($version )]($style)'
symbol = 'îš‹ '
style = 'bold 216'

# Package
[package]
format = '[$symbol$version ]($style)'
symbol = 'î¬© '
style = 'bold 202'

# Cloud Provider
[aws]
format = '[$symbol$profile( \[î´€ $region\])( \[î„ $duration\]) ]($style)'
symbol = 'î­ '
style = 'bold bright-yellow'

[azure]
format = '[$symbol($subscription) ]($style)'
symbol = 'î¯˜ '
style = 'bold blue'

[gcloud]
format = '[$symbol$account(@$domain)(#$project)( \[î´€ $region\]) ]($style)'
symbol = 'ó±‡¶ '
style = 'bold bright-blue'

# Terminal
[line_break]
disable = false

[username]
format = '[$user@]($style)'
style_root = 'bold red'
style_user = 'bold yellow'

[hostname]
format = '[$hostname ]($style)'
style = 'bold green'
ssh_only = true

[localip]
disabled = false

# Command
[cmd_duration]
format = '[ó±‘ $duration]($style)'
show_miliseconds = true
disabled = true

# Operation System
[os]
format = '$symbol'
disabled = false

[os.symbols]
#AIX = "â¿ "
#Alpaquita = "ğŸ”” "
#AlmaLinux = "ğŸ’  "
#Alpine = "ğŸ”ï¸ "
Amazon = "[î­ ](blue)"
Android = "[ï…» ](bright-green)"
Arch = "[ó°£‡ ](bright-blue)"
Artix = "[ïŒŸ ](blue)"
#CachyOS = "ğŸ—ï¸ "
CentOS = "[îŠ ](purple)"
Debian = "[î½ ](red)"
#DragonFly = "ğŸ‰ "
#Emscripten = "ğŸ”— "
#EndeavourOS = "ğŸš€ "
Fedora = "[îŸ™ ](blue)"
FreeBSD = "[ïŠ ](red)"
Garuda = "[ïŒ· ](dimmed yellow)"
Gentoo = "[îŸ¦ ](white)"
#HardenedBSD = "ğŸ›¡ï¸ "
#Illumos = "ğŸ¦ "
Kali = "[ïŒ§ ](blue)"
Linux = "[î¯† ](white)"
#Mabox = "ğŸ“¦ "
Macos = "[îœ‘ ](white)"
Manjaro = "[ïŒ’ ](green)"
#Mariner = "ğŸŒŠ "
#MidnightBSD = "ğŸŒ˜ "
Mint = "[ó°£­ ](bright-green)"
#NetBSD = "ğŸš© "
NixOS = "[î¡ƒ ](cyan)"
#Nobara = "ğŸ© "
OpenBSD = "[ïŒ¨ ](yellow)"
#OpenCloudOS = "â˜ï¸ "
#openEuler = "ğŸ¦‰ "
openSUSE = "[î¡— ](bright-green)"
OracleLinux = "[îœ’ ](red)"
Pop = "[ïŒª ](blue)"
Raspbian = "[îœ¢ ](red)"
Redhat = "[î½ ](bright-red)"
RedHatEnterprise = "[î½ ](red)"
#RockyLinux = "ğŸ’  "
#Redox = "ğŸ§ª "
#Solus = "â›µ "
SUSE = "[î¡— ](bright-green)"
Ubuntu = "[î½² ](196)"
#Ultramarine = "ğŸ”· "
Unknown = "[? ](bright-red)"
#Uos = "ğŸ² "
Void = "[ïŒ® ](dimmed green)"
Windows = "[î˜ª ](blue)"
